### PR TITLE
httpproxy test image can setup TLS client with CA certs

### PR DESCRIPTION
**Pull request by mgencur**
Env variables that are required for proper functioning:
UPSTREAM_CA_CERT - name of the Secret that includes CA certificate to be
used by the client
SERVER_NAME - openssl subjectAltName to be used by the client to verify
the server DNS

# Changes

- If CA_CERT env variable is passed the client configures TLS for connecting to the server
- The usage is demonstrated in https://github.com/knative-sandbox/net-kourier/pull/909

/kind enhancement

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Review by nak3 — COMMENTED** [review]
Thank you so much!
Could you add a brief usage for this in https://github.com/knative/networking/blob/main/test/conformance/ingress/README.md ?
Otherwise, LGTM.

**Comment by mgencur** [comment]
@nak3 Sure. Let me add a few notes there.

**Comment by mgencur** [comment]
/hold
For one more little change - make SERVER_NAME fully optional.

**Pull request merged**
