### PR TITLE
Removes unwanted timeout setting

### PR DESCRIPTION
**Pull request by richterdavid**
Remove setting KIngress timeout per comments from @vagababov and @tcnghia in slack: 
https://knative.slack.com/archives/CA9RHBGJX/p1592591518025100

### CODE REVIEW

**Comment by vagababov** [comment]
And I presume your other change will permit setting this timeout _if_ I want to?

**Comment by richterdavid** [comment]
@vagababov IIUC yes, though we should talk on that PR about how default timeouts fit into the picture.
https://github.com/knative/serving/pull/8203

**Comment by vagababov** [comment]
/lgtm
I'll let Nghia approve,.

**Comment by tcnghia** [comment]
/hold
until tomorrow

/approve

**Pull request merged**
