### PR TITLE
include helpers to lookup annotations

### PR DESCRIPTION
**Pull request by dprotaso**
this should enable supporting multiple keys

### CODE REVIEW

**Comment by nak3** [comment]
I'm a little bit confused. It will become https://github.com/knative/networking/pull/562/files#diff-da8358898a61a0564b9d8d16c9a08bfe7acbfea66006fb6753b0f44b8c20ba1cR117-R163 eventually?

**Comment by dprotaso** [comment]
Switching to the helper will make it easier to transition without breaking things.

I don't think we want to drop support for the old casing unless we perform some migration.

**Comment by nak3** [comment]
Thank you. I understand what I misunderstood. The function in [pull/562](https://github.com/knative/networking/pull/562) uses `pkg/configmap.Parse` and `configmap.AsString` but it just parse annotations, not configmap` at all.
I misunderstood as how annotation parse will be changed to configmap parse :sweat:

**Comment by dprotaso** [comment]
That other PR is a WIP - i realize the code is simply enough so I dropped
the use of the configmap package

**Comment by dprotaso** [comment]
*in this PR

**Comment by dprotaso** [comment]
But yeah I was using that package to parse values from the annotations

**Pull request merged**
