### PR TITLE
Move network conformance tests to knative.dev/networking

### PR DESCRIPTION
**Pull request by tcnghia**
/assign @dprotaso 

Changes in the PR:

* Move prober package and constants to knative.dev/networking. Probing is part of the conformance runtime so it's best to live here.
* Move conformance tests to knative.dev/networking.

### CODE REVIEW

**Comment by vagababov** [comment]
meh
` Please run ./hack/update-codegen.sh`

**Comment by dprotaso** [comment]
you'd want to pull in https://github.com/knative/serving/pull/8592

**Comment by tcnghia** [comment]
/hold

I'm going to stage the downstream changes first

**Comment by tcnghia** [comment]
/close

I'm breaking this to smaller PR to be less surgical.

**Pull request closed without merging**
