### PR TITLE
Remove Istio specific constants (to be moved to net-istio).

### PR DESCRIPTION
**Pull request by JRBANCEL**
Move Istio stuff to `net-istio`.
Unless I missed a repository, this is only used in `net-istio`.

Wait for corresponding `net-istio` PR.
/hold
/assign @tcnghia

### CODE REVIEW

**Comment by JRBANCEL** [comment]
@tcnghia do you know why the `/lgtm` and `/approve` of @ZhiminXiang are not adding labels?
He is in the OWNERS file.

**Comment by JRBANCEL** [comment]
@ZhiminXiang can you retry the command, there was a Prow issue earlier.

**Comment by tcnghia** [comment]
This OWNERS file is out of sync with https://github.com/knative/serving/blob/master/OWNERS_ALIASES . I've created https://github.com/knative/networking/pull/106 to sync.

**Pull request merged**
