### PR TITLE
Replace all usages of deprecated wait.PollImmediate with wait.PollUntilContextTimeout

### PR DESCRIPTION
**Pull request by prashantrewar**
# Changes

- Replace usages of deprecated wait.PollImmediate with wait.PollUntilContextTimeout

/kind <kind>

Fixes #

**Release Note**

```release-note
NONE
```

**Docs**

```docs

```

### CODE REVIEW

**Comment by dprotaso** [comment]
I believe the test is failing because `wait.ErrWaitTimeout` is not longer returned by these new functions

https://github.com/knative/networking/blob/13c6ea7211e1702121c36cd88c3c049e4eeb6515/pkg/prober/prober_test.go#L227-L229


According to the docs https://pkg.go.dev/k8s.io/apimachinery/pkg/util/wait#Poll
> Note that the new method will no longer return ErrWaitTimeout and instead return errors defined by the context package. Will be removed in a future release.

**Comment by dprotaso** [comment]
You'll also need to verify if `wait.ErrWaitTimeout` is used anywhere in the serving/net- repo and update those accordingly.

**Comment by dprotaso** [comment]
I don't think it's used anywhere in code that isn't tests so I think we should be ok

**Comment by ReToCode** [comment]
@prashantrewar mind taking a look at the test failures?

**Comment by dprotaso** [comment]
@prashantrewar just following up - are you able to address the unit test failures?

**Comment by dprotaso** [comment]
> Should I replace this also?
Yeah update the test

**Comment by prashantrewar** [comment]
> > Should I replace this also?
> 
> Yeah update the test

@dprotaso Done!

**Comment by dprotaso** [comment]
/lgtm
/approve

thanks @prashantrewar

**Comment by prashantrewar** [comment]
Thank you @dprotaso for guidance and support.

**Pull request merged**
